# Generated by Django 3.1.6 on 2021-02-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='resume',
            field=models.ImageField(null=True, upload_to='Resume-Image/'),
        ),
    ]
