# Generated by Django 3.1.6 on 2021-02-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='field',
            field=models.CharField(choices=[('P', 'Programmer'), ('T', 'Tailor'), ('M', 'Mechanical Engineer'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='field',
            field=models.CharField(choices=[('P', 'Programmer'), ('T', 'Tailor'), ('M', 'Mechanical Engineer'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
