# Generated by Django 3.1.6 on 2021-02-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='owner_company',
            new_name='company',
        ),
    ]
